export enum ReactQueryKeysEnum {
  AGENDAMENTO_FINDALL = "useFindAllAgendamento",
  AGENDAMENTO_CREATE = "useCreateAgendamento",
  AGENDAMENTO_UPDATE = "useUpdateAgendamento",
  AGENDAMENTO_DELETE = "useDeleteAgendamento",
  AGENDAMENTO_FINDBYID = "useFindAgendamentoById",
  USUARIO_FINDALL = "useFindAllUsuario",
  USUARIO_CREATE = "useCreateUsuario",
  USUARIO_UPDATE = "useUpdateUsuario",
  USUARIO_DELETE = "useDeleteUsuario",
  USUARIO_FINDBYID = "useFindUsuarioById",
  SOLICITANTE_FINDALL = "useFindAllSolicitante",
  SOLICITANTE_CREATE = "useCreateSolicitante",
  SOLICITANTE_UPDATE = "useUpdateSolicitante",
  SOLICITANTE_DELETE = "useDeleteSolicitante",
  SOLICITANTE_FINDBYID = "useFindSolicitanteById",
  SALA_FINDALL = "useFindAllSala",
  SALA_CREATE = "useCreateSala",
  SALA_UPDATE = "useUpdateSala",
  SALA_DELETE = "useDeleteSala",
  SALA_FINDBYID = "useFindSalaById",
}
